/*
 * Copyright 2017-2024 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Library
 * This is a library API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package example.micronaut.controller;


import example.micronaut.api.DefaultApi;
import example.micronaut.model.Product;
import io.micronaut.http.HttpResponse;
import jakarta.validation.Valid;

import java.util.List;

@io.micronaut.http.annotation.Controller
public class Controller implements DefaultApi {

    @Override
    public List<@Valid Product> productsGet() {
        return List.of();
    }

    @Override
    public HttpResponse<@Valid Product> productsPost(Product product) {
        return null;
    }

    @Override
    public HttpResponse<Void> productsProductIdDelete(Integer productId) {
        return null;
    }

    @Override
    public Product productsProductIdGet(Integer productId) {
        return null;
    }

    @Override
    public Product productsProductIdPut(Integer productId, Product product) {
        return null;
    }
}

